apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- cloud-native-pg.yaml
- home-assistant.yaml
- q-media.yaml
- q-redis.yaml
- synapse.yaml
- synapse-gateway.yaml
- devpi.yaml
- linkwarden.yaml
- immich.yaml
- q-postgres.yaml
- arc.yaml
- arc-secret.yaml
- ip-sentry.yaml
- graylog.yaml
- authentik.yaml
