apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkwarden
spec:
  suspended: true
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/private-ops.git'
    path: linkwarden
    targetRevision: main
  destination:
    namespace: linkwarden
    name: in-cluster
  # syncPolicy:
  #   syncOptions:
  #     - CreateNamespace=true
