apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: q-postgres
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/private-ops.git'
    path: q-postgres
    targetRevision: main
  destination:
    namespace: q-postgres
    name: in-cluster
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /spec/affinity
        - /spec/bootstrap
        - /spec/enablePDB
        - /spec/enableSuperuserAccess
        - /spec/failoverDelay
        - /spec/imageName
        - /spec/logLevel
        - /spec/postgresGID
        - /spec/postgresUID
        - /spec/primaryUpdateMethod
        - /spec/probes
        - /spec/replicationSlots
        - /spec/smartShutdownTimeout
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
