apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synapse
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/private-ops.git'
    path: synapse/matrix-stack
    targetRevision: main
    helm:
      valueFiles:
        - ../values-colfax.yaml
  destination:
    namespace: synapse
    name: in-cluster
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: synapse-synapse-main
      jsonPointers:
        - /spec/updateStrategy/rollingUpdate
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
