apiVersion: v2
name: nginx-gateway-fabric-private
description: NGINX Gateway Fabric - private internal gateway (replaces ingress-nginx-private)
type: application
version: 0.0.1
appVersion: 2.4.2

dependencies:
- name: nginx-gateway-fabric
  repository: https://helm.nginx.com/stable
  version: 2.4.2
