version: '3'
tasks:

  check-k:
    cmds:
      - |
        echo "Checking cluster/argocd"
        kustomize build cluster/argocd

        echo "Checking cluster/bedrock/gateway-api-crds"
        kustomize build cluster/bedrock/gateway-api-crds

        echo "Checking cluster/sandbox/mosquitto"
        kustomize build cluster/sandbox/mosquitto

        echo "Checking cluster/sandbox/github-runners"
        kustomize build cluster/sandbox/github-runners

    silent: true

  setup-helm:
    cmds:
      - |
        helm repo add jetstack https://charts.jetstack.io
        helm repo add fluent https://fluent.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo add harbor https://helm.goharbor.io
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
    silent: true

  check-helm:
    deps: [setup-helm]
    cmds:
      - |
        echo "Checking cert-manager"
        helm dependency build cluster/bedrock/cert-manager
        helm lint cluster/bedrock/cert-manager -f cluster/bedrock/cert-manager/values-colfax.yaml

        echo "Checking fluentbit"
        helm dependency build cluster/bedrock/fluentbit
        helm lint cluster/bedrock/fluentbit -f cluster/bedrock/fluentbit/values-colfax.yaml

        echo "Checking ingress-private"
        helm dependency build cluster/bedrock/ingress/ingress-private
        helm lint cluster/bedrock/ingress/ingress-private -f cluster/bedrock/ingress/ingress-private/values-colfax.yaml

        echo "Checking ingress-public"
        helm dependency build cluster/bedrock/ingress/ingress-public
        helm lint cluster/bedrock/ingress/ingress-public -f cluster/bedrock/ingress/ingress-public/values-colfax.yaml

        echo "Checking nginx-gateway-fabric/private"
        helm dependency build cluster/bedrock/nginx-gateway-fabric/private
        helm lint cluster/bedrock/nginx-gateway-fabric/private -f cluster/bedrock/nginx-gateway-fabric/private/values-colfax.yaml

        echo "Checking nginx-gateway-fabric/public"
        helm dependency build cluster/bedrock/nginx-gateway-fabric/public
        helm lint cluster/bedrock/nginx-gateway-fabric/public -f cluster/bedrock/nginx-gateway-fabric/public/values-colfax.yaml

        echo "Checking monitoring/prometheus-stack"
        helm dependency build cluster/bedrock/monitoring/prometheus-stack
        helm lint cluster/bedrock/monitoring/prometheus-stack -f cluster/bedrock/monitoring/prometheus-stack/values-colfax.yaml

        echo "Checking storage/nfs-client"
        helm dependency build cluster/bedrock/storage/nfs-client
        helm lint cluster/bedrock/storage/nfs-client -f cluster/bedrock/storage/nfs-client/values-colfax.yaml

        echo "Checking harbor"
        helm dependency build cluster/sandbox/harbor
        helm lint cluster/sandbox/harbor -f cluster/sandbox/harbor/values-colfax.yaml

    silent: true
