apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: harbor-client-settings
  namespace: harbor
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: harbor
  body:
    maxSize: "0"
  keepAlive:
    timeout:
      server: 600s
