---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-oidc-secret
  namespace: harbor
spec:
  encryptedData:
    oidc_client_secret: AgDJQ92YM5pj2K+Mbjdcl9FeTYXf1enKunGmSoJaMSlt/Pg1Hqot3lSwG9bTk9htsd/IIR2ijZOu/4fmvmLb9f0H9714fHr4sfKCmH5gncTqfnnkXC4UbutfdC2XVtGKZdsCRUtZArwyJqEOJtJZ8C7C05af1buVJQk4fuCyXak+KIZUPGYD3hQxChTm9rvj6j1pRIdm6tThEdtlBCEiKquNuLKc6lnnOyeQPU2lMApnURMNY7W0Bd5FpNHHNPixfAi1gQUsMym5bkfp52Wh0irAVraKm+gRCOtHTmBMlnxh4EKfOAEersMjajCRw+g0kSTWC5duKKWTdk3r3ziXActR4mufeNzdVAid8LXS9jkGOifmX7zoHIlJVEQr95rXfxin+seu6Lx9TIJLLTFGT3kMiMO35uHr77u6/si3vTEHDEnqcpVeqCSIDYVZ1f/DEPEJv66w5aAhkzvMBs5p3qHf5+YCDoxvmef5EzwN32DuHWZOXRrtVM0ypupUyVTY2anl7T4gsO5+H2yLCh9PGA6Rk407R8/cIauG5dg2AD4qGOabdhCrzF1Hb9v83eoWpC8p+cETiN7YSNqI0VF2xugqvqs9stt2ECE0GfPjSQ1MGNE5IeMo1+GwahDid6bhfrKwXTqzWDx+CCf4rgQrpV/Z1uRFLwh+cnYtAVrYSKnq/FmnTX4IJLRB/d7byWGZLVuWaQMO1b9u1JvI90ubyystAeWyg14toEVSHxjN0XFCNtEooe5RCOEv2aBZmQ==
  template:
    metadata:
      name: harbor-oidc-secret
      namespace: harbor
    type: Opaque
