---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-auth
  namespace: harbor
spec:
  encryptedData:
    password: AgBimNuKR3V3Aed9NQvBN5nqdH2IpdDO5kPAHVEno2CwzWYbEC3Pn+remnfDHfYXNDgqiD+iDSp6aVIsaYG/a+rMnypyvMLlcSIES33GYp4zRBKlKdAejbFYVtUv3JYlUx876mnPXDBX5yhCzWrQe40zXXc6Kym8YEi4e+Wm9CpG6rv47xhq1pT6IXfTKUm2johzbmOBEnLfICCGnmgN65E7xIhCgETbiQbzrimQ5YuTKi050DkA+dt80/pVOCuPZGYYjq9DTYATVUGOCmatfN+707PUz5cCRpmtKbSDJaM1VovWouIrmFB/+h4YdBuJuuC+/hufA5cadVST6pGhcunmX6RZrU5ZSVDYf16QytrZqodO6wmhUCLXHh37EC+N1rPrGYl2YfiMJrHHjo7f4Pw3p3ZBc8KOp08NROzDuvriRV8RDY8gnYxxYmEQHBfKIawXUz6HNcX9dIhNtuFQ6OjPnr7rOwCcDWCxH8ANNKZ3kzGT1gjj+XDSZ368N6YCCt46tqnPplbo5ZOI0zYcRnvq6HPh4FN6bbWdtBM0WWV/6PKf/YbutdMSNDGO1f9DP5KR/XFx23yna//y29TVn6482pchRA3fESIyJ+K2U5rz5627sLAhDbtiPbrHJ/1SSaF0CpN96nR+CQHv87i2tat+vb40e/Db8eNqOcKpjB8UTn5hqrqMWojjJjzTfEym8UO38pOxFQUQ2/GXUildXNrg8i/pUUn3k9ZB
  template:
    metadata:
      name: harbor-admin-auth
      namespace: harbor
    type: Opaque
