Vagrant.configure("2") do |config|
  config.ssh.insert_key = true
  config.ssh.username = "vagrant"
  config.ssh.password = "somepassword"
  config.ssh.forward_agent = true
  config.vm.network "public_network", ip: "192.168.50.79"
  config.vm.define "green-machine" do |worker|
    worker.vm.box = "bento/ubuntu-22.04"
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8000"
    vb.cpus = "6"
  end
  # config.vm.network "public_network"
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("/home/kube/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end
end
