apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- argocd.yaml
- cert-manager.yaml
- nfs-client.yaml
- fluentbit.yaml
- gateway-api-crds.yaml
- nginx-gateway-fabric-private.yaml
- nginx-gateway-fabric-public.yaml
- prometheus-stack.yaml
- blackbox-exporter.yaml
- sealed-secrets.yaml
- metallb.yaml
