apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric-private
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/colfax-ops.git'
    path: cluster/bedrock/nginx-gateway-fabric/private
    targetRevision: main
    helm:
      skipCrds: true
      valueFiles:
        - values-colfax.yaml
  destination:
    namespace: nginx-gateway-fabric-private
    name: in-cluster
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /metadata/labels
        - /metadata/annotations
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
