# NFS-Client Colfax Values
nfs-subdir-external-provisioner:
  nfs:
    server: 192.168.50.52
    path: /mnt/media-1/container-data/
    mountOptions:
    - nolock
    volumeName: nfs-subdir-external-provisioner-root
    # Reclaim policy for the main nfs volume
    reclaimPolicy: Retain

  storageClass:
    defaultClass: true

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - galapago
