apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: private-tls
spec:
  secretName: private-tls
  issuerRef:
    name: private-ca
    kind: ClusterIssuer
  dnsNames:
    - "*.colfax.int"
    - "*.stocky.colfax.int"
