---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-grafana-oauth
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgCQ9bfbqf8giqp9rDDuzpG3uXE5TWov7TOYIae9Zfu8CgUAxw4e4UKVdtYLk58m77YyjloGH3JO7eyh53p9yReOOQTpjVGDlCY/YU9ibh9JG+VZUgcFXHtk9+I8GXkq5bl5vkSL8bv7AIE5zlCDBVqqIXPdSUBlqE/BoJ9oCE1ZdB7EveAPYeuC+87ln2RYmZVbq71s68h9cTqPa6lj5TP0nQr+HV7/OvD+NQaxRFlO1SILvX8nJXAJ3RV9ADtET9u01/frMf2qzDna2+i/s64miuBXCVBqj1SGHHoySIEsU1AIdji+hA7KwnJZE5rxFYIC5A1W3K8bxPG0BOLotL40BrH0BwBNN/RQrRfGKsXp1dpAtEAO0owa40FVFWtnrxYsolawK+IDotZsNlaU0sHWr+qW+xGWGbohaTpcVJ7D1SenDh75uczv15fRfHURL2VsNTd2SvY2gfy1dLrdJFFNzg1qWJb02uLEtmGl5ND0ZfWYLihzCV2cDfSohSVBcItxmk+UQdRmGB90RfW3QPoG7QPZdQKfC084UHSD6mpJ7lNNqK4K+397XRbqCsbu+numQhekJ+bb3FabnMe3teRshL1P2h43m4gD+ZcWwN6s5rVCzGsXdJNSzB1qc23bLF8Eyq+eZRATc9xc1giqlBsGgOVHPKLbFqL3jUDgP/mT2uAJUWQr1BGlrFGWXuk5s9ewfESJF3n8fgLlkF4UXb3nikjHLiiFczuC7GWJ8Bvh1A==
  template:
    metadata:
      name: authentik-grafana-oauth
      namespace: monitoring
    type: Opaque
