---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-postgres-secret
  namespace: monitoring
spec:
  encryptedData:
    GF_DATABASE_PASSWORD: AgCd+g+zZ+HssRSYV+hP52EG9SaB4cqa16TwnqdQCGXTCdNStlysoBY6hrZ9hqnzvtWtVz0wfvOqqg8yaZeWgH6yp3+Wi/c1oCxHs4YGO/GXj3EhsyvcnrtCBs4DuFa/japyoZDcW42tgeD0hzpT7TdwNiO7+VsM7niqyCpRjJvZSxX1xj4OrsvbOqYg8yqlfmkwKba/hRMQPQTLufanhzhoWiHVlLvkG76Y9p5O2bMVLnWn1mVlUTXAVEidmwFVFHVq0mXihSq6dX2sVEKcAjFJLzZgHzLiiiaN3qo90HFusyYCo6oNxk4TJgujXMsMa4NOXzkV3eNG1rf6MlBTuhyEbxjJpiSke+icNmqwixTVwmKbsQyTrBNQxkhuxMXhL2pQ2+v9gSEPnaO9INDoPhw6VOpESK1j82j3r1LJAYsDDcie6Za76ThtPbF2xM6VZ6KAFvofw7HVRzK/Uo/3BCpYxRkxz9aGm/pW/aV0UJwRHlNyJo75lgTQ5OR0nE1J4s1eaS/TXHfO1KkbXhh2ZLWwm8B27Qrnv0CRvmlYOCR1DPK29IqaCxLBkxkpVfKng82K80j4PxzgXOZYuZWWjwtTL7IJtykEfJG3ljwqnAihelDfh3WXrkx+QSiDjiMqj0gxsG6TB4DgjENfS9DEyz3KTv/wrJVD/LzGUL4pBubH9OpFx5h+2l38cP6GMVdGFZoCDWm7uGYqvtoOrJE+/AlJN3tgoisodcC75/v+CQ4=
  template:
    metadata:
      name: grafana-postgres-secret
      namespace: monitoring
    type: Opaque
