---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-authentik-oidc
  namespace: argocd
spec:
  encryptedData:
    oidc.authentik.clientSecret: AgBoA6BqxyhSCVHXaAAETCi2WT1tKbMTjnQduEnBBVjTnKkVwC80n53GT6gMp3DAdb04Hy8XxdROj5/m7TAFZsuE6YD7ftVPCdcODQcJZd0Yp3CGSWCCoDgbCUnNK4brsw2TI4Efs5QlOmUxwoN+iccTAOWSIcPdcojhuisnfx00xomFpliKRZ5JEEdNfj073EdQNxmjnrIpLfFEfqf8QZ4GwDBOltrgbi5X1sFaWMW4osn7eELalEXyOgd8zz0N+BWV4EvjHf2RaO53JZzdkSHTlNsSRtKz5Nu7wChJGIIjlrDzKsPXn1Pbncovy7mtLySRdXC1yQlktZqvXVRutWeeuaDT/ZQXGxsS4rX1qaZH45M1BHxvIIdJwkTzjT0meBFaYD8Uh+GZ1KYQ0BeX1pJCn2SN0N7oDTKgR3Tj2dLfvFyX05g+NkFa4sXcK1hapfsdHkEIVQmHUtNYSW9YM4rHbZK3Q+wNlpnb6QGKKc2u1WJUaa980NWTyWN/Qx6XRqFnfiCBC/JOBCM+SHzR1UuFOZZO+Gwu/wYA6XicTrA8HbS87MpgicaXgLYiFNepOWzCjKsVwd0q688Fycj7tUblTmHnXFfilrQXSEpXUH7p7502phKtKxlNjUqCxbE6gt24hJ0R8HwcBFiB0Rp2JZn7ka52nJzEX2BB436qKUSIG7hCh5ZoR6l14c5eGddTfmJYRWaSado5CDzsYHFe2xO0zUtZw98b6G2+owISjFVK+9AYCh2NTviiLx3QLA==
  template:
    metadata:
      name: argocd-authentik-oidc
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
    type: Opaque
