apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-tls
spec:
  secretName: public-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "alix.lol"
    - "api.alix.lol"
    - "stocky.alix.lol"
    - "api.stocky.alix.lol"
    - "api-dev.alix.lol"
    - "jellyfin.alix.lol"
    - "photos.alix.lol"
    - "linkwarden.alix.lol"
    - "graylog.alix.lol"
    - "auth.alix.lol"
    - "squid-ink.us"
    - "ha.squid-ink.us"
    - "harbor.squid-ink.us"
    - "matrix.squid-ink.us"
    - "offline.gold"
    - "matrix.offline.gold"
    - "account.offline.gold"
