apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-public
  namespace: nginx-gateway-fabric-public
spec:
  gatewayClassName: nginx-public
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: public-tls
      allowedRoutes:
        namespaces:
          from: All
  addresses:
    - type: IPAddress
      value: 192.168.50.80
